apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: anomaly-detection
  identifier: anomaly-detection
  description: CCM anomaly detection backend service
  annotations:
    github.com/project-slug: juanrigonz/crc-rdhd
    argocd/app-name: 'hello'
spec:
  type: service
  owner: group:guest
  lifecycle: experimental
