apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-test-component # O el nombre correspondiente (ej. anomaly-detection)
  annotations:
    # Esta es la anotación obligatoria para habilitar los plugins de GitHub
    github.com/project-slug: "Juanrigonz/crc-rdhd"
    
    # Esta anotación hace que el botón "View Source" apunte al lugar correcto
    backstage.io/source-location: "url:https://github.com/Juanrigonz/crc-rdhd"
spec:
  type: service
  lifecycle: experimental
  owner: developer/Juanrigonz
