apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  labels:
    app.kubernetes.io/name: backstage
  name: developer-hub
  namespace: rhdh-operator
spec:
  application:
    appConfig:
      configMaps:
        - name: rhdh-app-config
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: rhdh-dynamic-plugins
    extraEnvs:
      secrets:
        - name: my-secrets-rhdh
    extraFiles:
      configMaps:
        - key: ca.crt
          mountPath: /etc/ssl/certs/crc-ca.crt
          name: crc-ca
      mountPath: /opt/app-root/src
    route:
      enabled: true
      host: developerhub.apps-crc.testing
  monitoring:
    enabled: false

