kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-app-config
  namespace: rhdh-operator
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  app-config.yaml: |
    app:
      title: Farmacias de Guadalajara
      baseUrl: https://developerhub.apps-crc.testing/
    auth:
      environment: development
      session:
        secret: ${AUTH_SESSION_SECRET}
      providers:
        # guest:
        #   dangerouslyAllowOutsideDevelopment: true
        oidc:
          development:
            metadataUrl: ${OIDC_BASE_KEYCLOAK_URL}/realms/${OIDC_KEYCLOAK_REALM}/.well-known/openid-configuration
            clientId: ${AUTH_OIDC_CLIENT_ID}
            clientSecret: ${AUTH_OIDC_CLIENT_SECRET}
            prompt: auto
            dangerouslyAllowSignInWithoutUserInCatalog: true
            signIn:
              resolvers:
                - resolver: preferredUsernameMatchingUserEntityName
    signInPage: oidc
    backend:
      csp:
        connect-src:
        - '''self'''
        - 'http:'
        - 'https:'
        - 'data:'
        img-src:
        - '''self'''
        - 'data:'
        - 'https://cdn.worldvectorlogo.com'
        script-src:
        - '''self'''
        - '''unsafe-inline'''
        - '''unsafe-eval'''
        script-src-elem:
        - '''self'''
        - '''unsafe-inline'''
        - '''unsafe-eval'''
      auth:
        externalAccess:
        - options:
            secret: pl4s3Ch4ng3M3
            subject: legacy-default-config
          type: legacy
      baseUrl: https://developerhub.apps-crc.testing/
      cors:
        origin: https://developerhub.apps-crc.testing/
    catalog:
      locations:
        - rules:
          - allow:
            - Resource
          target: https://github.com/redhat-developer/red-hat-developer-hub-software-templates/blob/main/templates/github/argocd/template.yaml
          type: url
      providers:
        keycloakOrg:
          default:
            realm: ${OIDC_KEYCLOAK_REALM}
            loginRealm: ${OIDC_KEYCLOAK_REALM}
            baseUrl: ${OIDC_BASE_KEYCLOAK_URL}
            clientId: ${AUTH_OIDC_CLIENT_ID}
            clientSecret: ${AUTH_OIDC_CLIENT_SECRET}
            schedule:
              frequency: { minutes: 1 }
              timeout: { minutes: 1 }
              initialDelay: { seconds: 15 }
            userTransformer: sanitizeEmailTransformer
          
